### ISSUE TITLE
Did I do something wrong?

### ISSUE THREAD

**Issue by nosferatu500** [vite-plugin/vite-plugin-esmodule#7]
```
import { builtinModules } from "module";
import { defineConfig } from "vite";
import esmodule from "vite-plugin-esmodule";
import pkg from "../package.json";

export default defineConfig({
    root: __dirname,
    plugins: [esmodule(["execa", { "file-type": "file-type/index.js" }, "p-map"], { webpack: true })],
    build: {
        outDir: "../build",
        lib: {
            entry: "electron.ts",
            formats: ["cjs"],
            fileName: () => "[name].cjs",
        },
        rollupOptions: {
            external: ["electron", ...builtinModules, ...Object.keys(pkg.dependencies || {})],
        },
    },
});
```

```
import { fileTypeFromFile } from "file-type";

'fileTypeFromFile' is not exported by node_modules/file-type/browser.js, imported by electron/electron.ts
```

**Comment by nosferatu500** [comment]
v1.4.3

// Config
```
export default defineConfig({
    root: __dirname,
    plugins: [esmodule(["execa", "p-map", { "file-type": "file-type/index.js" }])],
    build: {
        outDir: "../build",
        lib: {
            entry: "electron.ts",
            formats: ["cjs"],
            fileName: () => "[name].cjs",
        },
        rollupOptions: {
            external: ["electron", ...builtinModules, ...Object.keys(pkg.dependencies || {})],
        },
    },
});
```


// Error:
```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './index.js' is not defined by "exports" in /Users/user/Documents/GitHub/test_project/node_modules/file-type/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at /Users/user/Documents/GitHub/test_project/node_modules/vite-plugin-esmodule/index.js:104:22
    at Array.reduce (<anonymous>)
    at buildESModules (/Users/user/Documents/GitHub/test_project/node_modules/vite-plugin-esmodule/index.js:99:27) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

@caoxiemeihao

**Comment by nosferatu500** [comment]
The error occurs after `vite build`

**Comment by caoxiemeihao** [comment]
Move `file-type`  to `devDependencies`

**Comment by nosferatu500** [comment]
it's already in `devDependencies `

**Comment by nosferatu500** [comment]
I think vite by default importing `browser.js`, not `index.js` file

**Comment by caoxiemeihao** [comment]
Upgrade to `v1.4.4`

**Comment by nosferatu500** [comment]
Same issue :(

**Comment by nosferatu500** [comment]
I can prepare a test repo for you for experiments if needed.

**Comment by nosferatu500** [comment]
repo for experiments
[esmodule-test](https://github.com/nosferatu500/electron-vite-ts-esm)

@caoxiemeihao

**Comment by caoxiemeihao** [comment]
```diff
- plugins: [esmodule(["execa", "p-map", {"file-type": "file-type/index.js"}])],
+ plugins: [esmodule(["execa", "p-map", "file-type"])],
```

**Comment by nosferatu500** [comment]
@caoxiemeihao 

Thanks, now it's working but I get another one error with other module.

When I trying to using `stringToStream `
```
ipcMain.handle("stringToStream", async (_event, ffmpegPath: string, ffmpegArgs: string[], filePath: string) => {
    const process = execa(ffmpegPath, ffmpegArgs);

    const { default: stringToStream } = await import("string-to-stream");

    stringToStream(filePath).pipe(process.stdin);

    const result = await process;
    return result.stdout;
});
```

I got next error:
```
Error occurred in handler for 'stringToStream': TypeError: node_process__WEBPACK_IMPORTED_MODULE_3__.cwd is not a function
```

I don't have this issue on v1.2.4

**Comment by nosferatu500** [comment]
`string-to-stream` installed in `dependency` and not part of esmodule["other-module"]

**Comment by caoxiemeihao** [comment]
What is `v1.2.4`?
If you import `string-to-stream` in Main-process, there will be no restrictions.

**Comment by nosferatu500** [comment]
[vite-plugin-esmodule](https://github.com/vite-plugin/vite-plugin-esmodule) v1.2.4

The error occur when I trying to call `stringToStream` (not just import). The error doesn't occur on `vite-plugin-esmodule v 1.2.4` but occur in `v1.4.4`

**Comment by caoxiemeihao** [comment]
> If you import string-to-stream in Main-process, there will be no restrictions.

This will have nothing to do with `vite-plugin-esmodule`

**Comment by nosferatu500** [comment]
this [snippet](https://github.com/vite-plugin/vite-plugin-esmodule/issues/7#issuecomment-1284730649)
from Main-Process

**Comment by caoxiemeihao** [comment]
In Main-process, `string-to-stream` does not require any Pre-processing.

**Comment by nosferatu500** [comment]
I will update the repo example later for better understanding.

In short. When I using `string-to-stream` I getting error from `vite-plugin-esmodule` in watch mode. The error occurs after I upgrading from v1.2.4 to 1.4.4.

**Comment by caoxiemeihao** [comment]
You can hoist the `string-to-stream` to TOP of this file.
